### ISSUE TITLE
Extra tabindex="0" on section elements

### ISSUE THREAD

**Issue by marcysutton** [patrickarlt/accessible-js-api-app#1]
Great job with this! One thing I noticed right away was the extra tab stops on the sections within the sidebar. Changing `tabindex="0"` to `tabindex="-1"` would make those regions focusable by script but pull them out of the keyboard tab order. That would help both keyboard and screen reader users since those items are not actionable.

**Comment by patrickarlt** [comment]
@marcysutton That is great advice thank you! I always forget that `tabindex="-1"` can still be focused by scripts but the change works out great!

I'm honestly pretty flattered that you took the time to check this out and comment. You sparked my interest in accessibility with your web components talk at JS Conf one year and I've been working it into my projects more and more ever since.
